/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Analysis
 */
export interface Analysis {
    /**
     * 
     * @type {string}
     * @memberof Analysis
     */
    description?: string;
    /**
     * 
     * @type {object}
     * @memberof Analysis
     */
    parametersSchema: object;
    /**
     * 
     * @type {string}
     * @memberof Analysis
     */
    preset: string;
    /**
     * 
     * @type {string}
     * @memberof Analysis
     */
    subProcessor: string;
    /**
     * 
     * @type {string}
     * @memberof Analysis
     */
    title?: string;
    /**
     * 
     * @type {string}
     * @memberof Analysis
     */
    readonly url?: string;
    /**
     * 
     * @type {string}
     * @memberof Analysis
     */
    readonly uuid?: string;
}

export function AnalysisFromJSON(json: any): Analysis {
    return AnalysisFromJSONTyped(json, false);
}

export function AnalysisFromJSONTyped(json: any, ignoreDiscriminator: boolean): Analysis {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'description': !exists(json, 'description') ? undefined : json['description'],
        'parametersSchema': json['parameters_schema'],
        'preset': json['preset'],
        'subProcessor': json['sub_processor'],
        'title': !exists(json, 'title') ? undefined : json['title'],
        'url': !exists(json, 'url') ? undefined : json['url'],
        'uuid': !exists(json, 'uuid') ? undefined : json['uuid'],
    };
}

export function AnalysisToJSON(value?: Analysis | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'description': value.description,
        'parameters_schema': value.parametersSchema,
        'preset': value.preset,
        'sub_processor': value.subProcessor,
        'title': value.title,
    };
}


