/* tslint:disable */
/* eslint-disable */
/**
 * TimeSide API
 * RESTful API of TimeSide, a scalable audio processing framework.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Experience
 */
export interface Experience {
    /**
     * 
     * @type {string}
     * @memberof Experience
     */
    title?: string;
    /**
     * 
     * @type {string}
     * @memberof Experience
     */
    readonly uuid?: string;
    /**
     * 
     * @type {string}
     * @memberof Experience
     */
    readonly url?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof Experience
     */
    presets?: Array<string>;
    /**
     * 
     * @type {boolean}
     * @memberof Experience
     */
    isPublic?: boolean;
    /**
     * 
     * @type {string}
     * @memberof Experience
     */
    author?: string | null;
}

export function ExperienceFromJSON(json: any): Experience {
    return ExperienceFromJSONTyped(json, false);
}

export function ExperienceFromJSONTyped(json: any, ignoreDiscriminator: boolean): Experience {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'title': !exists(json, 'title') ? undefined : json['title'],
        'uuid': !exists(json, 'uuid') ? undefined : json['uuid'],
        'url': !exists(json, 'url') ? undefined : json['url'],
        'presets': !exists(json, 'presets') ? undefined : json['presets'],
        'isPublic': !exists(json, 'is_public') ? undefined : json['is_public'],
        'author': !exists(json, 'author') ? undefined : json['author'],
    };
}

export function ExperienceToJSON(value?: Experience | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'title': value.title,
        'presets': value.presets,
        'is_public': value.isPublic,
        'author': value.author,
    };
}


