/* tslint:disable */
/* eslint-disable */
/**
 * TimeSide API
 * RESTful API of TimeSide,                 a scalable audio processing framework
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ItemWaveform
 */
export interface ItemWaveform {
    /**
     * 
     * @type {string}
     * @memberof ItemWaveform
     */
    readonly itemUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof ItemWaveform
     */
    title?: string;
    /**
     * 
     * @type {string}
     * @memberof ItemWaveform
     */
    readonly waveform?: string;
    /**
     * 
     * @type {string}
     * @memberof ItemWaveform
     */
    readonly waveformImageUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof ItemWaveform
     */
    readonly waveformUrl?: string;
}

export function ItemWaveformFromJSON(json: any): ItemWaveform {
    return ItemWaveformFromJSONTyped(json, false);
}

export function ItemWaveformFromJSONTyped(json: any, ignoreDiscriminator: boolean): ItemWaveform {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'itemUrl': !exists(json, 'item_url') ? undefined : json['item_url'],
        'title': !exists(json, 'title') ? undefined : json['title'],
        'waveform': !exists(json, 'waveform') ? undefined : json['waveform'],
        'waveformImageUrl': !exists(json, 'waveform_image_url') ? undefined : json['waveform_image_url'],
        'waveformUrl': !exists(json, 'waveform_url') ? undefined : json['waveform_url'],
    };
}

export function ItemWaveformToJSON(value?: ItemWaveform | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'title': value.title,
    };
}


