/* tslint:disable */
/* eslint-disable */
/**
 * TimeSide API
 * RESTful API of TimeSide, a scalable audio processing framework.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ItemWaveformWaveform
 */
export interface ItemWaveformWaveform {
    /**
     * 
     * @type {Array<number>}
     * @memberof ItemWaveformWaveform
     */
    maxValues: Array<number>;
    /**
     * 
     * @type {Array<number>}
     * @memberof ItemWaveformWaveform
     */
    minValues: Array<number>;
    /**
     * 
     * @type {number}
     * @memberof ItemWaveformWaveform
     */
    nbPixels: number;
    /**
     * 
     * @type {number}
     * @memberof ItemWaveformWaveform
     */
    start?: number;
    /**
     * 
     * @type {number}
     * @memberof ItemWaveformWaveform
     */
    stop?: number;
    /**
     * 
     * @type {Array<number>}
     * @memberof ItemWaveformWaveform
     */
    timeValues: Array<number>;
}

export function ItemWaveformWaveformFromJSON(json: any): ItemWaveformWaveform {
    return ItemWaveformWaveformFromJSONTyped(json, false);
}

export function ItemWaveformWaveformFromJSONTyped(json: any, ignoreDiscriminator: boolean): ItemWaveformWaveform {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'maxValues': json['max_values'],
        'minValues': json['min_values'],
        'nbPixels': json['nb_pixels'],
        'start': !exists(json, 'start') ? undefined : json['start'],
        'stop': !exists(json, 'stop') ? undefined : json['stop'],
        'timeValues': json['time_values'],
    };
}

export function ItemWaveformWaveformToJSON(value?: ItemWaveformWaveform | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'max_values': value.maxValues,
        'min_values': value.minValues,
        'nb_pixels': value.nbPixels,
        'start': value.start,
        'stop': value.stop,
        'time_values': value.timeValues,
    };
}


