/* tslint:disable */
/* eslint-disable */
/**
 * TimeSide API
 * RESTful API of TimeSide, a scalable audio processing framework.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ItemList
 */
export interface ItemList {
    /**
     * 
     * @type {string}
     * @memberof ItemList
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof ItemList
     */
    mimeType?: string;
    /**
     * 
     * @type {string}
     * @memberof ItemList
     */
    readonly playerUrl?: string;
    /**
     * Audio file to process.
     * @type {Blob}
     * @memberof ItemList
     */
    sourceFile?: Blob;
    /**
     * URL of a streamable audio source to process.
     * @type {string}
     * @memberof ItemList
     */
    sourceUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof ItemList
     */
    title?: string;
    /**
     * 
     * @type {string}
     * @memberof ItemList
     */
    readonly url?: string;
    /**
     * 
     * @type {string}
     * @memberof ItemList
     */
    readonly uuid?: string;
}

export function ItemListFromJSON(json: any): ItemList {
    return ItemListFromJSONTyped(json, false);
}

export function ItemListFromJSONTyped(json: any, ignoreDiscriminator: boolean): ItemList {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'description': !exists(json, 'description') ? undefined : json['description'],
        'mimeType': !exists(json, 'mime_type') ? undefined : json['mime_type'],
        'playerUrl': !exists(json, 'player_url') ? undefined : json['player_url'],
        'sourceFile': !exists(json, 'source_file') ? undefined : json['source_file'],
        'sourceUrl': !exists(json, 'source_url') ? undefined : json['source_url'],
        'title': !exists(json, 'title') ? undefined : json['title'],
        'url': !exists(json, 'url') ? undefined : json['url'],
        'uuid': !exists(json, 'uuid') ? undefined : json['uuid'],
    };
}

export function ItemListToJSON(value?: ItemList | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'description': value.description,
        'mime_type': value.mimeType,
        'source_file': value.sourceFile,
        'source_url': value.sourceUrl,
        'title': value.title,
    };
}


