/* tslint:disable */
/* eslint-disable */
/**
 * TimeSide API
 * RESTful API of TimeSide, a scalable audio processing framework.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Preset
 */
export interface Preset {
    /**
     * 
     * @type {string}
     * @memberof Preset
     */
    readonly url?: string;
    /**
     * 
     * @type {string}
     * @memberof Preset
     */
    readonly uuid?: string;
    /**
     * 
     * @type {string}
     * @memberof Preset
     */
    processor?: string | null;
    /**
     * 
     * @type {object}
     * @memberof Preset
     */
    parameters?: object;
}

export function PresetFromJSON(json: any): Preset {
    return PresetFromJSONTyped(json, false);
}

export function PresetFromJSONTyped(json: any, ignoreDiscriminator: boolean): Preset {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'url': !exists(json, 'url') ? undefined : json['url'],
        'uuid': !exists(json, 'uuid') ? undefined : json['uuid'],
        'processor': !exists(json, 'processor') ? undefined : json['processor'],
        'parameters': !exists(json, 'parameters') ? undefined : json['parameters'],
    };
}

export function PresetToJSON(value?: Preset | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'processor': value.processor,
        'parameters': value.parameters,
    };
}


