/* tslint:disable */
/* eslint-disable */
/**
 * TimeSide API
 * RESTful API of TimeSide, a scalable audio processing framework.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ResultVisualization
 */
export interface ResultVisualization {
    /**
     * 
     * @type {string}
     * @memberof ResultVisualization
     */
    subprocessorId?: string;
    /**
     * 
     * @type {number}
     * @memberof ResultVisualization
     */
    readonly start?: number;
    /**
     * 
     * @type {number}
     * @memberof ResultVisualization
     */
    readonly stop?: number;
    /**
     * 
     * @type {number}
     * @memberof ResultVisualization
     */
    readonly width?: number;
    /**
     * 
     * @type {number}
     * @memberof ResultVisualization
     */
    readonly height?: number;
}

export function ResultVisualizationFromJSON(json: any): ResultVisualization {
    return ResultVisualizationFromJSONTyped(json, false);
}

export function ResultVisualizationFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResultVisualization {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'subprocessorId': !exists(json, 'subprocessor_id') ? undefined : json['subprocessor_id'],
        'start': !exists(json, 'start') ? undefined : json['start'],
        'stop': !exists(json, 'stop') ? undefined : json['stop'],
        'width': !exists(json, 'width') ? undefined : json['width'],
        'height': !exists(json, 'height') ? undefined : json['height'],
    };
}

export function ResultVisualizationToJSON(value?: ResultVisualization | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'subprocessor_id': value.subprocessorId,
    };
}


