/* tslint:disable */
/* eslint-disable */
/**
 * TimeSide API
 * RESTful API of TimeSide, a scalable audio processing framework.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SubProcessor
 */
export interface SubProcessor {
    /**
     * 
     * @type {string}
     * @memberof SubProcessor
     */
    readonly url?: string;
    /**
     * 
     * @type {string}
     * @memberof SubProcessor
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof SubProcessor
     */
    processor?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SubProcessor
     */
    subProcessorId: string;
}

export function SubProcessorFromJSON(json: any): SubProcessor {
    return SubProcessorFromJSONTyped(json, false);
}

export function SubProcessorFromJSONTyped(json: any, ignoreDiscriminator: boolean): SubProcessor {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'url': !exists(json, 'url') ? undefined : json['url'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'processor': !exists(json, 'processor') ? undefined : json['processor'],
        'subProcessorId': json['sub_processor_id'],
    };
}

export function SubProcessorToJSON(value?: SubProcessor | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'processor': value.processor,
        'sub_processor_id': value.subProcessorId,
    };
}


