/* tslint:disable */
/* eslint-disable */
/**
 * TimeSide API
 * RESTful API of TimeSide, a scalable audio processing framework.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Task
 */
export interface Task {
    /**
     * 
     * @type {string}
     * @memberof Task
     */
    readonly url?: string;
    /**
     * 
     * @type {string}
     * @memberof Task
     */
    readonly uuid?: string;
    /**
     * Experience prossessed in the task.
     * @type {string}
     * @memberof Task
     */
    experience?: string | null;
    /**
     * Selection prossessed in the task.
     * @type {string}
     * @memberof Task
     */
    selection?: string | null;
    /**
     * Task\'s status:  failed: 0  draft: 1  pending: 2  running: 3  done: 4
     * @type {number}
     * @memberof Task
     */
    status?: TaskStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof Task
     */
    author?: string | null;
    /**
     * Single item prossessed in the task.
     * @type {string}
     * @memberof Task
     */
    item?: string | null;
}

export function TaskFromJSON(json: any): Task {
    return TaskFromJSONTyped(json, false);
}

export function TaskFromJSONTyped(json: any, ignoreDiscriminator: boolean): Task {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'url': !exists(json, 'url') ? undefined : json['url'],
        'uuid': !exists(json, 'uuid') ? undefined : json['uuid'],
        'experience': !exists(json, 'experience') ? undefined : json['experience'],
        'selection': !exists(json, 'selection') ? undefined : json['selection'],
        'status': !exists(json, 'status') ? undefined : json['status'],
        'author': !exists(json, 'author') ? undefined : json['author'],
        'item': !exists(json, 'item') ? undefined : json['item'],
    };
}

export function TaskToJSON(value?: Task | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'experience': value.experience,
        'selection': value.selection,
        'status': value.status,
        'author': value.author,
        'item': value.item,
    };
}

/**
* @export
* @enum {string}
*/
export enum TaskStatusEnum {
    NUMBER_0 = 0,
    NUMBER_1 = 1,
    NUMBER_2 = 2,
    NUMBER_3 = 3,
    NUMBER_4 = 4
}


